### ISSUE TITLE
MissingMethodException on AuthenticationService.Authenticate call

### ISSUE THREAD

**Issue by supoved** [Charcoals/PivotalTracker.NET#17]
The example code from about page throws error on AuthenticationService.Authenticate call:
MissingMethodException: Method not found: 'Void RestSharp.RestClient.set_BaseUrl(System.String)'.

**Comment by kajalp** [comment]
This is because of an upgrade to restsharp.. using 14.4 version makes that work but the other step var stories = new StoryService(authenticationToken).GetAllStories(projectId); doesn't work.
