### ISSUE TITLE
Use Charcoals Travis-CI, not mine!

### ISSUE THREAD

**Issue by palfrey** [Charcoals/PivotalTracker.NET#20]
Merging #18 means the badge is currently referring to the build of my fork of this, when it should refer to the Charcoals account Travis-CI build. That build needs to be enabled by someone in the organisation.

**Comment by AlexCuse** [comment]
No one in the organization is currently using this code.  I may look into it for my own edification but it will not be a priority.

I'm trying to find someone to take over this project, any interest?

**Comment by palfrey** [comment]
Not really, no. I did the v5 work when I was working for an organisation that was almost entirely a Windows shop and it was useful for something internal. These days, I don't really do much .Net stuff, and my spare time is already pretty full!

**Comment by Hyldahl** [comment]
I'm using this at my current job. I'll be happy to take over the project.

**Comment by Hyldahl** [comment]
Removed the link to palfrey Travis-CI build.
