### ISSUE TITLE
Issue with dates and json

### ISSUE THREAD

**Issue by Nixon-Joseph** [Charcoals/PivotalTracker.NET#23]
I am getting this exception thrown on every date 
`[DateField] = '(new System.Collections.Generic.Mscorlib_CollectionDebugView<PivotalTrackerDotNet.Domain.Story>(stories).Items[0]).[DateField]' threw an exception of type 'System.FormatException'`
Using the exact story getting code listed on the home page of this project. I'm guessing you have the api set up to get the milli date, instead of the standard one. Can you add some overload to get the standard date format? XML is fine reading this format, but I am not using XML.
![2017-11-13_16-51-37](https://user-images.githubusercontent.com/10250222/32753598-1ce9d5fc-c893-11e7-8924-547d35589ac4.jpg)

**Comment by Nixon-Joseph** [comment]
I've forked your project and added 2 methods to the storyService that specifically get certain date types; you'll probably want to change up how it's done, but it works.
https://github.com/Nixon-Joseph/PivotalTracker.NET

**Comment by Hyldahl** [comment]
Thanks, I'll take a look.

**Comment by Hyldahl** [comment]
From the screenshot it looks like either you a wrapping the library with your own code and maybe modified the library your self.
The Story object doesn't have AcceptedOn, CreatedOn projects and there is no Note object.

Therefore I have no idea of what you code is doing to cause this issue.
Also from the screenshot it does look like AcceptedAt CreatedAt properties have been deserialized correctly.

**Comment by Nixon-Joseph** [comment]
Hmm, maybe that's changed since I posted that. Because I didn't change the models at all.
